version: '3.8'

services:
  # 1. User Service
  user-service:
    image: messenger-user:latest
    container_name: user-service
    network_mode: "host"
    restart: "no"
    env_file: ./user/.env

  # 2. Core Service
  core-service:
    image: messenger-core:latest
    container_name: core-service
    network_mode: "host"
    restart: "no"
    env_file: ./core/.env

  # 3. Common Service
  common-service:
    image: messenger-common:latest
    container_name: common-service
    network_mode: "host"
    restart: "no"
    env_file: ./common/.env

  # 4. Auth Service
  auth-service:
    image: messenger-auth:latest
    container_name: auth-service
    network_mode: "host"
    restart: "no"
    env_file: ./auth/.env

  # 5. Organization Service
  org-service:
    image: messenger-org:latest
    container_name: org-service
    network_mode: "host"
    restart: "no"
    env_file: ./org/.env
    volumes:
      - /path/on/host/storage/org_files:/app/storage/org_files

  # 6. Admin Service
  admin-service:
    image: messenger-admin:latest
    container_name: admin-service
    network_mode: "host"
    restart: "no"
    env_file: ./admin/.env

  # 7. Message Service
  message-service:
    image: messenger-message:latest
    container_name: message-service
    network_mode: "host"
    restart: "no"
    env_file: ./message/.env

  # 8. Batch Service
  batch-service:
    image: messenger-batch:latest
    container_name: batch-service
    network_mode: "host"
    restart: "no"
    env_file: ./batch/.env

  # 9. Notificator Service
  notificator-service:
    image: messenger-notificator:latest
    container_name: notificator-service
    network_mode: "host"
    restart: "no"
    env_file: ./notificator/.env

  # 10. File Service
  file-service:
    image: messenger-file:latest
    container_name: file-service
    network_mode: "host"
    restart: "no"
    env_file: ./file/.env
    volumes:
      - ./file/private.key:/run/secrets/jwt_private_key:ro