// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/file_service_upload_file_check.proto

// package는 **"이 대화(API)의 주제가 무엇인가"**를 정의하는 것이지, 현재 내가 작업 중인 서비스 이름을 적는 게 아닙니다.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 요청할 때 보낼 데이터
type UploadFileCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckDate     string                 `protobuf:"bytes,1,opt,name=checkDate,proto3" json:"checkDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileCheckRequest) Reset() {
	*x = UploadFileCheckRequest{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileCheckRequest) ProtoMessage() {}

func (x *UploadFileCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileCheckRequest.ProtoReflect.Descriptor instead.
func (*UploadFileCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileCheckRequest) GetCheckDate() string {
	if x != nil {
		return x.CheckDate
	}
	return ""
}

// 응답으로 받을 데이터
type UploadFileCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileCheckResponse) Reset() {
	*x = UploadFileCheckResponse{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileCheckResponse) ProtoMessage() {}

func (x *UploadFileCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileCheckResponse.ProtoReflect.Descriptor instead.
func (*UploadFileCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 요청할 때 보낼 데이터
type ClearFileStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearFileIds  []string               `protobuf:"bytes,1,rep,name=clear_file_ids,json=clearFileIds,proto3" json:"clear_file_ids,omitempty"`
	SendedFileIds []string               `protobuf:"bytes,2,rep,name=sended_file_ids,json=sendedFileIds,proto3" json:"sended_file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearFileStorageRequest) Reset() {
	*x = ClearFileStorageRequest{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearFileStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFileStorageRequest) ProtoMessage() {}

func (x *ClearFileStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFileStorageRequest.ProtoReflect.Descriptor instead.
func (*ClearFileStorageRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{2}
}

func (x *ClearFileStorageRequest) GetClearFileIds() []string {
	if x != nil {
		return x.ClearFileIds
	}
	return nil
}

func (x *ClearFileStorageRequest) GetSendedFileIds() []string {
	if x != nil {
		return x.SendedFileIds
	}
	return nil
}

// 응답으로 받을 데이터
type ClearFileStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearFileStorageResponse) Reset() {
	*x = ClearFileStorageResponse{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearFileStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearFileStorageResponse) ProtoMessage() {}

func (x *ClearFileStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearFileStorageResponse.ProtoReflect.Descriptor instead.
func (*ClearFileStorageResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{3}
}

func (x *ClearFileStorageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearFileStorageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 요청할 때 보낼 데이터
type GetInvalidFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Yesterday     string                 `protobuf:"bytes,1,opt,name=yesterday,proto3" json:"yesterday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvalidFileInfoRequest) Reset() {
	*x = GetInvalidFileInfoRequest{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvalidFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvalidFileInfoRequest) ProtoMessage() {}

func (x *GetInvalidFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvalidFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInvalidFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{4}
}

func (x *GetInvalidFileInfoRequest) GetYesterday() string {
	if x != nil {
		return x.Yesterday
	}
	return ""
}

// 응답으로 받을 데이터
type GetInvalidFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvalidFileId []string               `protobuf:"bytes,1,rep,name=invalid_file_id,json=invalidFileId,proto3" json:"invalid_file_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvalidFileInfoResponse) Reset() {
	*x = GetInvalidFileInfoResponse{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvalidFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvalidFileInfoResponse) ProtoMessage() {}

func (x *GetInvalidFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvalidFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInvalidFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvalidFileInfoResponse) GetInvalidFileId() []string {
	if x != nil {
		return x.InvalidFileId
	}
	return nil
}

func (x *GetInvalidFileInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_file_service_upload_file_check_proto protoreflect.FileDescriptor

const file_proto_file_service_upload_file_check_proto_rawDesc = "" +
	"\n" +
	"*proto/file_service_upload_file_check.proto\x12\x0fuploadFileCheck\"6\n" +
	"\x16UploadFileCheckRequest\x12\x1c\n" +
	"\tcheckDate\x18\x01 \x01(\tR\tcheckDate\"M\n" +
	"\x17UploadFileCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x17ClearFileStorageRequest\x12$\n" +
	"\x0eclear_file_ids\x18\x01 \x03(\tR\fclearFileIds\x12&\n" +
	"\x0fsended_file_ids\x18\x02 \x03(\tR\rsendedFileIds\"N\n" +
	"\x18ClearFileStorageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x19GetInvalidFileInfoRequest\x12\x1c\n" +
	"\tyesterday\x18\x01 \x01(\tR\tyesterday\"^\n" +
	"\x1aGetInvalidFileInfoResponse\x12&\n" +
	"\x0finvalid_file_id\x18\x01 \x03(\tR\rinvalidFileId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd6\x02\n" +
	"\x16UploadFileCheckService\x12d\n" +
	"\x0fUploadFileCheck\x12'.uploadFileCheck.UploadFileCheckRequest\x1a(.uploadFileCheck.UploadFileCheckResponse\x12g\n" +
	"\x10ClearFileStorage\x12(.uploadFileCheck.ClearFileStorageRequest\x1a).uploadFileCheck.ClearFileStorageResponse\x12m\n" +
	"\x12GetInvalidFileInfo\x12*.uploadFileCheck.GetInvalidFileInfoRequest\x1a+.uploadFileCheck.GetInvalidFileInfoResponseB!Z\x1ffile/internal/infrastructure/pbb\x06proto3"

var (
	file_proto_file_service_upload_file_check_proto_rawDescOnce sync.Once
	file_proto_file_service_upload_file_check_proto_rawDescData []byte
)

func file_proto_file_service_upload_file_check_proto_rawDescGZIP() []byte {
	file_proto_file_service_upload_file_check_proto_rawDescOnce.Do(func() {
		file_proto_file_service_upload_file_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_service_upload_file_check_proto_rawDesc), len(file_proto_file_service_upload_file_check_proto_rawDesc)))
	})
	return file_proto_file_service_upload_file_check_proto_rawDescData
}

var file_proto_file_service_upload_file_check_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_file_service_upload_file_check_proto_goTypes = []any{
	(*UploadFileCheckRequest)(nil),     // 0: uploadFileCheck.UploadFileCheckRequest
	(*UploadFileCheckResponse)(nil),    // 1: uploadFileCheck.UploadFileCheckResponse
	(*ClearFileStorageRequest)(nil),    // 2: uploadFileCheck.ClearFileStorageRequest
	(*ClearFileStorageResponse)(nil),   // 3: uploadFileCheck.ClearFileStorageResponse
	(*GetInvalidFileInfoRequest)(nil),  // 4: uploadFileCheck.GetInvalidFileInfoRequest
	(*GetInvalidFileInfoResponse)(nil), // 5: uploadFileCheck.GetInvalidFileInfoResponse
}
var file_proto_file_service_upload_file_check_proto_depIdxs = []int32{
	0, // 0: uploadFileCheck.UploadFileCheckService.UploadFileCheck:input_type -> uploadFileCheck.UploadFileCheckRequest
	2, // 1: uploadFileCheck.UploadFileCheckService.ClearFileStorage:input_type -> uploadFileCheck.ClearFileStorageRequest
	4, // 2: uploadFileCheck.UploadFileCheckService.GetInvalidFileInfo:input_type -> uploadFileCheck.GetInvalidFileInfoRequest
	1, // 3: uploadFileCheck.UploadFileCheckService.UploadFileCheck:output_type -> uploadFileCheck.UploadFileCheckResponse
	3, // 4: uploadFileCheck.UploadFileCheckService.ClearFileStorage:output_type -> uploadFileCheck.ClearFileStorageResponse
	5, // 5: uploadFileCheck.UploadFileCheckService.GetInvalidFileInfo:output_type -> uploadFileCheck.GetInvalidFileInfoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_file_service_upload_file_check_proto_init() }
func file_proto_file_service_upload_file_check_proto_init() {
	if File_proto_file_service_upload_file_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_service_upload_file_check_proto_rawDesc), len(file_proto_file_service_upload_file_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_service_upload_file_check_proto_goTypes,
		DependencyIndexes: file_proto_file_service_upload_file_check_proto_depIdxs,
		MessageInfos:      file_proto_file_service_upload_file_check_proto_msgTypes,
	}.Build()
	File_proto_file_service_upload_file_check_proto = out.File
	file_proto_file_service_upload_file_check_proto_goTypes = nil
	file_proto_file_service_upload_file_check_proto_depIdxs = nil
}
