// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: proto/file_service_upload_file_check.proto

// package는 **"이 대화(API)의 주제가 무엇인가"**를 정의하는 것이지, 현재 내가 작업 중인 서비스 이름을 적는 게 아닙니다.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UploadFileCheckService_UploadFileCheck_FullMethodName    = "/uploadFileCheck.UploadFileCheckService/UploadFileCheck"
	UploadFileCheckService_ClearFileStorage_FullMethodName   = "/uploadFileCheck.UploadFileCheckService/ClearFileStorage"
	UploadFileCheckService_GetInvalidFileInfo_FullMethodName = "/uploadFileCheck.UploadFileCheckService/GetInvalidFileInfo"
)

// UploadFileCheckServiceClient is the client API for UploadFileCheckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 파일 서비스가 외부(Message 서비스 등)에 제공할 기능들
type UploadFileCheckServiceClient interface {
	// 파일 전송 상태를 업데이트하는 함수 (쪽지 전송 시 호출)
	UploadFileCheck(ctx context.Context, in *UploadFileCheckRequest, opts ...grpc.CallOption) (*UploadFileCheckResponse, error)
	ClearFileStorage(ctx context.Context, in *ClearFileStorageRequest, opts ...grpc.CallOption) (*ClearFileStorageResponse, error)
	GetInvalidFileInfo(ctx context.Context, in *GetInvalidFileInfoRequest, opts ...grpc.CallOption) (*GetInvalidFileInfoResponse, error)
}

type uploadFileCheckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadFileCheckServiceClient(cc grpc.ClientConnInterface) UploadFileCheckServiceClient {
	return &uploadFileCheckServiceClient{cc}
}

func (c *uploadFileCheckServiceClient) UploadFileCheck(ctx context.Context, in *UploadFileCheckRequest, opts ...grpc.CallOption) (*UploadFileCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileCheckResponse)
	err := c.cc.Invoke(ctx, UploadFileCheckService_UploadFileCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadFileCheckServiceClient) ClearFileStorage(ctx context.Context, in *ClearFileStorageRequest, opts ...grpc.CallOption) (*ClearFileStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearFileStorageResponse)
	err := c.cc.Invoke(ctx, UploadFileCheckService_ClearFileStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadFileCheckServiceClient) GetInvalidFileInfo(ctx context.Context, in *GetInvalidFileInfoRequest, opts ...grpc.CallOption) (*GetInvalidFileInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvalidFileInfoResponse)
	err := c.cc.Invoke(ctx, UploadFileCheckService_GetInvalidFileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadFileCheckServiceServer is the server API for UploadFileCheckService service.
// All implementations must embed UnimplementedUploadFileCheckServiceServer
// for forward compatibility.
//
// 파일 서비스가 외부(Message 서비스 등)에 제공할 기능들
type UploadFileCheckServiceServer interface {
	// 파일 전송 상태를 업데이트하는 함수 (쪽지 전송 시 호출)
	UploadFileCheck(context.Context, *UploadFileCheckRequest) (*UploadFileCheckResponse, error)
	ClearFileStorage(context.Context, *ClearFileStorageRequest) (*ClearFileStorageResponse, error)
	GetInvalidFileInfo(context.Context, *GetInvalidFileInfoRequest) (*GetInvalidFileInfoResponse, error)
	mustEmbedUnimplementedUploadFileCheckServiceServer()
}

// UnimplementedUploadFileCheckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUploadFileCheckServiceServer struct{}

func (UnimplementedUploadFileCheckServiceServer) UploadFileCheck(context.Context, *UploadFileCheckRequest) (*UploadFileCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFileCheck not implemented")
}
func (UnimplementedUploadFileCheckServiceServer) ClearFileStorage(context.Context, *ClearFileStorageRequest) (*ClearFileStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearFileStorage not implemented")
}
func (UnimplementedUploadFileCheckServiceServer) GetInvalidFileInfo(context.Context, *GetInvalidFileInfoRequest) (*GetInvalidFileInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvalidFileInfo not implemented")
}
func (UnimplementedUploadFileCheckServiceServer) mustEmbedUnimplementedUploadFileCheckServiceServer() {
}
func (UnimplementedUploadFileCheckServiceServer) testEmbeddedByValue() {}

// UnsafeUploadFileCheckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadFileCheckServiceServer will
// result in compilation errors.
type UnsafeUploadFileCheckServiceServer interface {
	mustEmbedUnimplementedUploadFileCheckServiceServer()
}

func RegisterUploadFileCheckServiceServer(s grpc.ServiceRegistrar, srv UploadFileCheckServiceServer) {
	// If the following call panics, it indicates UnimplementedUploadFileCheckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UploadFileCheckService_ServiceDesc, srv)
}

func _UploadFileCheckService_UploadFileCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadFileCheckServiceServer).UploadFileCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadFileCheckService_UploadFileCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadFileCheckServiceServer).UploadFileCheck(ctx, req.(*UploadFileCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadFileCheckService_ClearFileStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearFileStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadFileCheckServiceServer).ClearFileStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadFileCheckService_ClearFileStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadFileCheckServiceServer).ClearFileStorage(ctx, req.(*ClearFileStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadFileCheckService_GetInvalidFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvalidFileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadFileCheckServiceServer).GetInvalidFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadFileCheckService_GetInvalidFileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadFileCheckServiceServer).GetInvalidFileInfo(ctx, req.(*GetInvalidFileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UploadFileCheckService_ServiceDesc is the grpc.ServiceDesc for UploadFileCheckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadFileCheckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uploadFileCheck.UploadFileCheckService",
	HandlerType: (*UploadFileCheckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFileCheck",
			Handler:    _UploadFileCheckService_UploadFileCheck_Handler,
		},
		{
			MethodName: "ClearFileStorage",
			Handler:    _UploadFileCheckService_ClearFileStorage_Handler,
		},
		{
			MethodName: "GetInvalidFileInfo",
			Handler:    _UploadFileCheckService_GetInvalidFileInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/file_service_upload_file_check.proto",
}
