package consts

const (
	LOGIN_HEADER_AUTH_TOKEN = "X-NEO-AuthToken"
	LOGIN_HEADER_UUID       = "X-NEO-Uuid"

	AUTHORIZATION        = "Authorization"
	DEVICE_REFRESH_TOKEN = "DEVICE_REFRESH_TOKEN"
	DEVICE_ACCESSS_TOKEN = "DEVICE_ACCESS_TOKEN"

	USER_ID = "userId"
)
