// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: proto/batch_message.proto

// package file;은 **"이 대화(API)의 주제가 무엇인가"**를 정의하는 것이지, 현재 내가 작업 중인 서비스 이름을 적는 게 아닙니다.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BatchMessageService_GetSendFileInfo_FullMethodName = "/batchMessage.BatchMessageService/GetSendFileInfo"
)

// BatchMessageServiceClient is the client API for BatchMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 파일 서비스가 외부(Message 서비스 등)에 제공할 기능들
type BatchMessageServiceClient interface {
	// 파일 전송 상태를 업데이트하는 함수 (쪽지 전송 시 호출)
	GetSendFileInfo(ctx context.Context, in *GetSendFileInfoRequest, opts ...grpc.CallOption) (*GetSendFileInfoResponse, error)
}

type batchMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchMessageServiceClient(cc grpc.ClientConnInterface) BatchMessageServiceClient {
	return &batchMessageServiceClient{cc}
}

func (c *batchMessageServiceClient) GetSendFileInfo(ctx context.Context, in *GetSendFileInfoRequest, opts ...grpc.CallOption) (*GetSendFileInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSendFileInfoResponse)
	err := c.cc.Invoke(ctx, BatchMessageService_GetSendFileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatchMessageServiceServer is the server API for BatchMessageService service.
// All implementations must embed UnimplementedBatchMessageServiceServer
// for forward compatibility.
//
// 파일 서비스가 외부(Message 서비스 등)에 제공할 기능들
type BatchMessageServiceServer interface {
	// 파일 전송 상태를 업데이트하는 함수 (쪽지 전송 시 호출)
	GetSendFileInfo(context.Context, *GetSendFileInfoRequest) (*GetSendFileInfoResponse, error)
	mustEmbedUnimplementedBatchMessageServiceServer()
}

// UnimplementedBatchMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBatchMessageServiceServer struct{}

func (UnimplementedBatchMessageServiceServer) GetSendFileInfo(context.Context, *GetSendFileInfoRequest) (*GetSendFileInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSendFileInfo not implemented")
}
func (UnimplementedBatchMessageServiceServer) mustEmbedUnimplementedBatchMessageServiceServer() {}
func (UnimplementedBatchMessageServiceServer) testEmbeddedByValue()                             {}

// UnsafeBatchMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchMessageServiceServer will
// result in compilation errors.
type UnsafeBatchMessageServiceServer interface {
	mustEmbedUnimplementedBatchMessageServiceServer()
}

func RegisterBatchMessageServiceServer(s grpc.ServiceRegistrar, srv BatchMessageServiceServer) {
	// If the following call panics, it indicates UnimplementedBatchMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BatchMessageService_ServiceDesc, srv)
}

func _BatchMessageService_GetSendFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSendFileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatchMessageServiceServer).GetSendFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BatchMessageService_GetSendFileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatchMessageServiceServer).GetSendFileInfo(ctx, req.(*GetSendFileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BatchMessageService_ServiceDesc is the grpc.ServiceDesc for BatchMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "batchMessage.BatchMessageService",
	HandlerType: (*BatchMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSendFileInfo",
			Handler:    _BatchMessageService_GetSendFileInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/batch_message.proto",
}
