// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/batch_message.proto

// package file;은 **"이 대화(API)의 주제가 무엇인가"**를 정의하는 것이지, 현재 내가 작업 중인 서비스 이름을 적는 게 아닙니다.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 요청할 때 보낼 데이터
type GetSendFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIds       []string               `protobuf:"bytes,1,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSendFileInfoRequest) Reset() {
	*x = GetSendFileInfoRequest{}
	mi := &file_proto_batch_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSendFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSendFileInfoRequest) ProtoMessage() {}

func (x *GetSendFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batch_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSendFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSendFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_batch_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetSendFileInfoRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

// 응답으로 받을 데이터
type GetSendFileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FileInfo      []*FileInfo            `protobuf:"bytes,2,rep,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSendFileInfoResponse) Reset() {
	*x = GetSendFileInfoResponse{}
	mi := &file_proto_batch_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSendFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSendFileInfoResponse) ProtoMessage() {}

func (x *GetSendFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batch_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSendFileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSendFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_batch_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetSendFileInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSendFileInfoResponse) GetFileInfo() []*FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

// 응답 구조체
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	LineKey       string                 `protobuf:"bytes,2,opt,name=line_key,json=lineKey,proto3" json:"line_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_batch_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batch_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_batch_message_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileInfo) GetLineKey() string {
	if x != nil {
		return x.LineKey
	}
	return ""
}

var File_proto_batch_message_proto protoreflect.FileDescriptor

const file_proto_batch_message_proto_rawDesc = "" +
	"\n" +
	"\x19proto/batch_message.proto\x12\fbatchMessage\"3\n" +
	"\x16GetSendFileInfoRequest\x12\x19\n" +
	"\bfile_ids\x18\x01 \x03(\tR\afileIds\"h\n" +
	"\x17GetSendFileInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\tfile_info\x18\x02 \x03(\v2\x16.batchMessage.FileInfoR\bfileInfo\">\n" +
	"\bFileInfo\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bline_key\x18\x02 \x01(\tR\alineKey2u\n" +
	"\x13BatchMessageService\x12^\n" +
	"\x0fGetSendFileInfo\x12$.batchMessage.GetSendFileInfoRequest\x1a%.batchMessage.GetSendFileInfoResponseB\"Z batch/internal/infrastructure/pbb\x06proto3"

var (
	file_proto_batch_message_proto_rawDescOnce sync.Once
	file_proto_batch_message_proto_rawDescData []byte
)

func file_proto_batch_message_proto_rawDescGZIP() []byte {
	file_proto_batch_message_proto_rawDescOnce.Do(func() {
		file_proto_batch_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_batch_message_proto_rawDesc), len(file_proto_batch_message_proto_rawDesc)))
	})
	return file_proto_batch_message_proto_rawDescData
}

var file_proto_batch_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_batch_message_proto_goTypes = []any{
	(*GetSendFileInfoRequest)(nil),  // 0: batchMessage.GetSendFileInfoRequest
	(*GetSendFileInfoResponse)(nil), // 1: batchMessage.GetSendFileInfoResponse
	(*FileInfo)(nil),                // 2: batchMessage.FileInfo
}
var file_proto_batch_message_proto_depIdxs = []int32{
	2, // 0: batchMessage.GetSendFileInfoResponse.file_info:type_name -> batchMessage.FileInfo
	0, // 1: batchMessage.BatchMessageService.GetSendFileInfo:input_type -> batchMessage.GetSendFileInfoRequest
	1, // 2: batchMessage.BatchMessageService.GetSendFileInfo:output_type -> batchMessage.GetSendFileInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_batch_message_proto_init() }
func file_proto_batch_message_proto_init() {
	if File_proto_batch_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_batch_message_proto_rawDesc), len(file_proto_batch_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_batch_message_proto_goTypes,
		DependencyIndexes: file_proto_batch_message_proto_depIdxs,
		MessageInfos:      file_proto_batch_message_proto_msgTypes,
	}.Build()
	File_proto_batch_message_proto = out.File
	file_proto_batch_message_proto_goTypes = nil
	file_proto_batch_message_proto_depIdxs = nil
}
