// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/file_service_upload_file_check.proto

// package는 **"이 대화(API)의 주제가 무엇인가"**를 정의하는 것이지, 현재 내가 작업 중인 서비스 이름을 적는 게 아닙니다.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 요청할 때 보낼 데이터
type UploadFileCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckDate     string                 `protobuf:"bytes,1,opt,name=checkDate,proto3" json:"checkDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileCheckRequest) Reset() {
	*x = UploadFileCheckRequest{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileCheckRequest) ProtoMessage() {}

func (x *UploadFileCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileCheckRequest.ProtoReflect.Descriptor instead.
func (*UploadFileCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileCheckRequest) GetCheckDate() string {
	if x != nil {
		return x.CheckDate
	}
	return ""
}

// 응답으로 받을 데이터
type UploadFileCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileCheckResponse) Reset() {
	*x = UploadFileCheckResponse{}
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileCheckResponse) ProtoMessage() {}

func (x *UploadFileCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_upload_file_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileCheckResponse.ProtoReflect.Descriptor instead.
func (*UploadFileCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_service_upload_file_check_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_file_service_upload_file_check_proto protoreflect.FileDescriptor

const file_proto_file_service_upload_file_check_proto_rawDesc = "" +
	"\n" +
	"*proto/file_service_upload_file_check.proto\x12\x0fuploadFileCheck\"6\n" +
	"\x16UploadFileCheckRequest\x12\x1c\n" +
	"\tcheckDate\x18\x01 \x01(\tR\tcheckDate\"M\n" +
	"\x17UploadFileCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2~\n" +
	"\x16UploadFileCheckService\x12d\n" +
	"\x0fUploadFileCheck\x12'.uploadFileCheck.UploadFileCheckRequest\x1a(.uploadFileCheck.UploadFileCheckResponseB\"Z batch/internal/infrastructure/pbb\x06proto3"

var (
	file_proto_file_service_upload_file_check_proto_rawDescOnce sync.Once
	file_proto_file_service_upload_file_check_proto_rawDescData []byte
)

func file_proto_file_service_upload_file_check_proto_rawDescGZIP() []byte {
	file_proto_file_service_upload_file_check_proto_rawDescOnce.Do(func() {
		file_proto_file_service_upload_file_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_service_upload_file_check_proto_rawDesc), len(file_proto_file_service_upload_file_check_proto_rawDesc)))
	})
	return file_proto_file_service_upload_file_check_proto_rawDescData
}

var file_proto_file_service_upload_file_check_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_file_service_upload_file_check_proto_goTypes = []any{
	(*UploadFileCheckRequest)(nil),  // 0: uploadFileCheck.UploadFileCheckRequest
	(*UploadFileCheckResponse)(nil), // 1: uploadFileCheck.UploadFileCheckResponse
}
var file_proto_file_service_upload_file_check_proto_depIdxs = []int32{
	0, // 0: uploadFileCheck.UploadFileCheckService.UploadFileCheck:input_type -> uploadFileCheck.UploadFileCheckRequest
	1, // 1: uploadFileCheck.UploadFileCheckService.UploadFileCheck:output_type -> uploadFileCheck.UploadFileCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_file_service_upload_file_check_proto_init() }
func file_proto_file_service_upload_file_check_proto_init() {
	if File_proto_file_service_upload_file_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_service_upload_file_check_proto_rawDesc), len(file_proto_file_service_upload_file_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_service_upload_file_check_proto_goTypes,
		DependencyIndexes: file_proto_file_service_upload_file_check_proto_depIdxs,
		MessageInfos:      file_proto_file_service_upload_file_check_proto_msgTypes,
	}.Build()
	File_proto_file_service_upload_file_check_proto = out.File
	file_proto_file_service_upload_file_check_proto_goTypes = nil
	file_proto_file_service_upload_file_check_proto_depIdxs = nil
}
